# Generated by Django 4.0.1 on 2022-07-29 18:07

import ckeditor.fields
import ckeditor_uploader.fields
import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lang', models.CharField(choices=[('FR', 'FRANCHE'), ('AR', 'ARABIC')], default='FR', max_length=2)),
                ('title', models.CharField(default='', max_length=100)),
                ('photo', cloudinary.models.CloudinaryField(help_text='image size nice to be 300*338', max_length=255, verbose_name='media/uploads/products/')),
                ('product_short_desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('digital', models.BooleanField(default=False, null=True)),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('puslish', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category_parent', to='category.category')),
                ('recommend_product', models.ManyToManyField(default='non', related_name='product_recommend', to='category.RecommendProduct')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sub_category', to='category.subcategories')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(help_text='image size nice to be 300*338', max_length=255, verbose_name='media/uploads/products/')),
                ('product_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
