# Generated by Django 4.0.1 on 2022-01-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_products'),
        ('product', '0003_product_color_product_photo_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product_category', to='category.Category'),
        ),
    ]
