# Generated by Django 4.0.1 on 2022-01-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
