# Generated by Django 4.0.1 on 2022-01-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_tagproduct'),
        ('product', '0009_product_product_short_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(related_name='product_tag', to='category.TagProduct'),
        ),
    ]
