# Generated by Django 4.0.1 on 2022-02-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(help_text='image size nice to be 300*338', upload_to='media/uploads/products/'),
        ),
    ]
