# Generated by Django 4.0.1 on 2022-02-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_recommendproduct'),
        ('product', '0014_product_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recommend_product',
            field=models.ManyToManyField(default='non', related_name='product_recommend', to='category.RecommendProduct'),
        ),
    ]
