# Generated by Django 4.0.1 on 2022-02-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_short_desc',
            field=models.TextField(max_length=150),
        ),
    ]
