# Generated by Django 4.0.1 on 2022-02-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_product_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_short_desc',
            field=models.TextField(max_length=500),
        ),
    ]
