# Generated by Django 4.0.1 on 2022-02-20 17:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_product_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=cloudinary.models.CloudinaryField(help_text='image size nice to be 300*338', max_length=255, verbose_name='media/uploads/products/'),
        ),
    ]
