# Generated by Django 4.0.1 on 2022-02-20 20:26

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_category_level_category_lft_category_parent_and_more'),
        ('product', '0021_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(related_name='product_category', to='category.Category'),
        ),
    ]
