# Generated by Django 4.0.1 on 2022-02-23 22:44

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0018_category_level_category_lft_category_rght_and_more'),
        ('product', '0023_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='category.category'),
            preserve_default=False,
        ),
    ]
