# Generated by Django 4.0.1 on 2022-02-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0022_remove_category_level_remove_category_lft_and_more'),
        ('product', '0025_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product_category', to='category.Category'),
        ),
    ]
