# Generated by Django 4.0.1 on 2022-02-25 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
