# Generated by Django 4.0.1 on 2022-02-27 23:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_product_sub_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_short_desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
