# Generated by Django 4.0.1 on 2022-03-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_remove_product_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
