# Generated by Django 4.0.1 on 2022-03-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
