# Generated by Django 4.0.1 on 2022-03-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_productimages_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='image_name',
        ),
    ]
