# Generated by Django 4.0.1 on 2022-03-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='puslish',
            field=models.BooleanField(default=True),
        ),
    ]
