# Generated by Django 4.0.1 on 2022-03-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_product_puslish'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lang',
            field=models.CharField(choices=[('FR', 'FRANCHE'), ('AR', 'ARABIC')], default='FR', max_length=2),
        ),
    ]
