# Generated by Django 4.0.1 on 2022-08-04 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_01',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_01', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='user_02',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_02', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
