# Generated by Django 4.0.1 on 2022-08-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('chat', '0002_room_user_01_room_user_02'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user_01',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_01', to='user.profileuser'),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_02',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_02', to='user.profileuser'),
        ),
    ]
