# Generated by Django 4.0.1 on 2022-01-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='posts',
            new_name='products',
        ),
    ]
