# Generated by Django 4.0.1 on 2022-01-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_category_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_logo',
            field=models.ImageField(upload_to='media/uploads/categores'),
        ),
    ]
