# Generated by Django 4.0.1 on 2022-02-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_tagproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tage_name', models.CharField(default='non', max_length=255)),
            ],
        ),
    ]
