# Generated by Django 4.0.1 on 2022-02-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_recommendproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='tag_brand',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
