# Generated by Django 4.0.1 on 2022-02-20 11:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_alter_category_category_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='media/uploads/brands'),
        ),
    ]
