# Generated by Django 4.0.1 on 2022-02-23 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0020_rename_mptt_level_category_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
