# Generated by Django 4.0.1 on 2022-02-25 21:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0022_remove_category_level_remove_category_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='media/uploads/subcategories'),
        ),
    ]
