# Generated by Django 4.0.1 on 2022-04-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0024_alter_subcategories_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='thumbnail',
        ),
    ]
