# Generated by Django 4.0.1 on 2022-07-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='job',
            field=models.CharField(choices=[('vendor', 'vendror'), ('shipper', 'shipper')], default='vendor', max_length=8),
        ),
    ]
