# Generated by Django 4.0.1 on 2022-01-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profileuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='store_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
