# Generated by Django 4.0.1 on 2022-01-29 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_vendor'),
        ('user', '0003_alter_profileuser_email_alter_profileuser_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='product.product'),
            preserve_default=False,
        ),
    ]
