# Generated by Django 4.0.1 on 2022-01-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profileuser_product_profileuser_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
