# Generated by Django 4.0.1 on 2022-01-31 22:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profileuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
