# Generated by Django 4.0.1 on 2022-01-31 22:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profileuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='Refund_Policy',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='Return_Policy',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='Shipping_Policy',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
