# Generated by Django 4.0.1 on 2022-02-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_profileuser_sotre_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='store_name',
            field=models.SlugField(blank=True, default='store name', error_messages={'unique': 'The store must be unique '}, max_length=100, unique=True),
        ),
    ]
