# Generated by Django 4.0.1 on 2022-02-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_profileuser_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='sotre_banner',
            field=models.FileField(default='default/image.jpg', upload_to='media/uploads/vendors'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='sotre_logo',
            field=models.FileField(default='default/image.jpg', upload_to='media/uploads/vendors'),
        ),
    ]
