# Generated by Django 4.0.1 on 2022-02-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_profileuser_sotre_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='sotre_banner',
            field=models.ImageField(default='default/image.jpg', upload_to='media/uploads/vendors'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='sotre_logo',
            field=models.ImageField(default='default/image.jpg', upload_to='media/uploads/vendors'),
        ),
    ]
