# Generated by Django 4.0.1 on 2022-02-14 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_profileuser_sotre_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='store_name',
            field=models.CharField(blank=True, default=uuid.uuid1, error_messages={'unique': 'The store must be unique '}, max_length=100, unique=True),
        ),
    ]
