# Generated by Django 4.0.1 on 2022-07-28 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profileuser_job'),
        ('user', '0028_alter_profileuser_refund_policy_and_more'),
    ]

    operations = [
    ]
