# Generated by Django 4.0.1 on 2022-02-20 17:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_profileuser_refund_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='sotre_banner',
            field=cloudinary.models.CloudinaryField(default='default/1.jpg', max_length=255, verbose_name='media/uploads/vendors'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='sotre_logo',
            field=cloudinary.models.CloudinaryField(default='default/1.jpg', max_length=255, verbose_name='media/uploads/vendors'),
        ),
    ]
