# Generated by Django 4.0.1 on 2022-02-27 19:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_profileuser_sotre_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='sotre_banner',
            field=cloudinary.models.CloudinaryField(default='default/1.jpg', max_length=255, verbose_name='media/uploads/vendors'),
        ),
    ]
