# Generated by Django 4.0.1 on 2022-02-28 08:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_profileuser_sotre_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='Refund_Policy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='Return_Policy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='Shipping_Policy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
