# Generated by Django 4.0.1 on 2022-02-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_profileuser_facebook_link_profileuser_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
