# Generated by Django 4.0.1 on 2022-03-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_profileuser_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='watsapp_link',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
