# Generated by Django 4.0.1 on 2022-04-28 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_alter_profileuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='job',
            field=models.CharField(choices=[('vendor', 'vendro'), ('shipper', 'shipper')], default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
