# Generated by Django 4.0.1 on 2022-05-02 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileuser',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
