# Generated by Django 4.0.1 on 2022-07-28 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_merge_20220728_2325'),
        ('user', '0044_profileuser_created_profileuser_updated'),
    ]

    operations = [
    ]
