# Generated by Django 4.0.1 on 2022-07-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_merge_20220728_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='job',
            field=models.CharField(choices=[('vendor', 'vendror'), ('shipper', 'shipper')], max_length=8),
        ),
    ]
