# Generated by Django 4.0.1 on 2022-07-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_alter_profileuser_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='job',
            field=models.CharField(choices=[('vendor', 'vendror'), ('shipper', 'shipper')], max_length=7),
        ),
    ]
