# Generated by Django 4.0.1 on 2022-02-28 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_add_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='custemer_email',
            field=models.EmailField(default='email@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='custemer_name',
            field=models.TextField(default='custemer'),
            preserve_default=False,
        ),
    ]
