# Generated by Django 4.0.1 on 2022-02-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_alter_comment_custemer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['add_at']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
    ]
