# Generated by Django 4.0.1 on 2022-02-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_comment_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
    ]
