# Generated by Django 4.0.1 on 2022-03-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_remove_comment_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-add_at']},
        ),
    ]
