# Generated by Django 4.0.1 on 2022-08-04 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershipper',
            name='order_shipper',
        ),
        migrations.AddField(
            model_name='ordershipper',
            name='order_shipper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.profileuser'),
            preserve_default=False,
        ),
    ]
