# Generated by Django 4.0.1 on 2022-02-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_custemer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
    ]
