# Generated by Django 4.0.1 on 2022-02-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_shippingaddress_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-date_add',)},
        ),
        migrations.AlterField(
            model_name='custemer',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
