# Generated by Django 4.0.1 on 2022-02-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderitem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custemer',
            old_name='user',
            new_name='custemer',
        ),
    ]
