# Generated by Django 4.0.1 on 2022-02-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_user_custemer_custemer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custemer',
            old_name='custemer',
            new_name='user',
        ),
    ]
