# Generated by Django 4.0.1 on 2022-04-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_rename_custemer_custemer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Payment_status',
            field=models.CharField(choices=[('UN', 'Unpaid'), ('PD', 'Paid')], default='UN', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='Shipping_status',
            field=models.CharField(choices=[('DL', 'Delivered'), ('RT', 'Return'), ('NN', 'Unknown')], default='NN', max_length=2),
        ),
    ]
