# Generated by Django 4.0.1 on 2022-04-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_payment_status_order_shipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='Shipping_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Return', 'Return'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
    ]
