# Generated by Django 4.0.1 on 2022-05-06 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0013_alter_order_shipping_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myshipper', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshipperuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
