# Generated by Django 4.0.1 on 2022-05-06 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_ordershipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipper',
            name='ordershiper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshippeorder', to='order.order'),
        ),
    ]
