# Generated by Django 4.0.1 on 2022-05-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_profileuser_created_profileuser_updated'),
        ('order', '0015_ordershipper_ordershiper'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='myshipper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshipperuser', to='user.profileuser'),
        ),
        migrations.DeleteModel(
            name='OrderShipper',
        ),
    ]
