# Generated by Django 4.0.1 on 2022-05-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_profileuser_created_profileuser_updated'),
        ('order', '0016_order_myshipper_delete_ordershipper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='myshipper',
        ),
        migrations.AddField(
            model_name='order',
            name='myshipper',
            field=models.ManyToManyField(blank=True, null=True, related_name='myshipperuser', to='user.ProfileUser'),
        ),
    ]
