# Generated by Django 4.0.1 on 2022-05-07 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_profileuser_created_profileuser_updated'),
        ('order', '0019_remove_order_myshipper'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
                ('order_shipper', models.ManyToManyField(to='user.ProfileUser')),
            ],
        ),
    ]
